name: CI for HTML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kode
      uses: actions/checkout@v3

    - name: Validasi HTML
      uses: Cyb3r-Jak3/html5validator-action@v0.4.0
      with:
    directory: ./index.html
